# == APP CONFIGURATION == #
spring:
  application:
    name: Employee Management App

  # == DATABASE CONFIGURATION == #
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password: h2
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  # == H2 DB CONFIGURATION == #
  h2:
    console:
      enabled: true
      path: /h2-console