INSERT INTO DEPARTMENT (NAME, MANDATORY, READ_ONLY)
VALUES ('Organisation', TRUE, TRUE);

INSERT INTO EMPLOYEE (NAME_FIRST, NAME_LAST)
VALUES ('Jhon','Smith');

INSERT INTO EMPLOYEE (NAME_FIRST, NAME_LAST)
VALUES ('Jane','Doe');