CREATE TABLE EMPLOYEE
(
    ID         LONG DEFAULT NEXTVAL('SEQUENCE_EMPLOYEE') PRIMARY KEY,
    NAME_FIRST VARCHAR(255) NOT NULL,
    NAME_LAST  VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENT
(
    ID        LONG DEFAULT NEXTVAL('SEQUENCE_DEPARTMENT') PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL UNIQUE,
    MANDATORY BOOLEAN DEFAULT FALSE ,
    READ_ONLY BOOLEAN DEFAULT FALSE
);

CREATE TABLE EMPLOYEE_DEPARTMENT
(
    ID_EMPLOYEE   BIGINT,
    ID_DEPARTMENT BIGINT,
    PRIMARY KEY (ID_EMPLOYEE,ID_DEPARTMENT),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT (ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQUENCE_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_EMPLOYEE START WITH 1 INCREMENT BY 1;
