CREATE TABLE EMPLOYEE
(
    ID         LONG PRIMARY KEY,
    NAME_FIRST VARCHAR(255) NOT NULL,
    NAME_LAST  VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENT
(
    ID        LONG PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    MANDATORY BOOLEAN DEFAULT FALSE,
    READ_ONLY BOOLEAN DEFAULT FALSE
);

CREATE TABLE EMPLOYEE_DEPARTMENT
(
    ID            LONG PRIMARY KEY,
    ID_EMPLOYEE   BIGINT,
    ID_DEPARTMENT BIGINT,
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT (ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQUENCE_DEPARTMENT START WITH 2 INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_EMPLOYEE  START WITH 1 INCREMENT BY 1;
