CREATE TABLE EMPLOYEE
(
    ID         VARCHAR(36) PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENT
(
    ID        VARCHAR(36) PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    MANDATORY BOOLEAN DEFAULT FALSE,
    READ_ONLY BOOLEAN DEFAULT FALSE
);

CREATE TABLE EMPLOYEE_DEPARTMENT
(
    ID            VARCHAR(36) PRIMARY KEY,
    EMPLOYEE_ID   BIGINT,
    DEPARTMENT_ID BIGINT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID) ON DELETE CASCADE,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID) ON DELETE CASCADE
);
